
provers = [ "minisat-ml", "minisat", "msat", "z3", "batsat" ]

[minisat-ml]

binary = "./minisat.exe"
cmd = "./minisat.exe -cpu-lim $timeout $file"
unsat = "^UNSAT"
sat = "^SAT"
unknown = "INDETERMINATE"
version = "git:."

[minisat]

cmd = "minisat -cpu-lim=$timeout $file"
unsat = "^UNSATISFIABLE"
sat = "^SATISFIABLE"
unknown = "INDETERMINATE|INTERRUPTED"
version = "2.2"

[z3]

cmd = "./z3.sh $file -T:$timeout"
unsat = "^unsat$"
sat = "^sat$"
unknown = "^unknown$"
version = "4.8.4"

[batsat]

cmd = "batsat $file --cpu-lim $timeout"
unsat = "s UNSATISFIABLE"
sat = "s SATISFIABLE"
unknown = "s INDETERMINATE"
version = "0.0.2"

[msat]

cmd = "msat -time $timeout $file"
unsat = "^Unsat"
sat = "^Sat"
unknown = "Unknown"
version = "0.8"

[test]

timeout=30
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat", "z3", "batsat" ]
dir = [ "benchs/msat/" ]

expect = "program:minisat"

[bench-basic]

timeout=30
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat", "z3", "batsat" ]
dir = [ "benchs/basic" ]

expect = "unknown"

[bench-satrace-06]

timeout=300
memory = 5000
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat", "z3", "batsat" ]
dir = [ "benchs/sat_race_2006/" ]

expect = "unknown"

[bench-satcomp-18]

timeout=300
memory = 5000
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat", "z3", "batsat" ]
dir = [ "benchs/satcomp-18/" ]

expect = "unknown"
