
provers = [ "minisat-ml", "minisat", "msat", "z3" ]

[minisat-ml]

binary = "./minisat.exe"
cmd = "./minisat.exe -cpu-lim $timeout $file"
unsat = "^UNSAT"
sat = "^SAT"
unknown = "INDETERMINATE"
version = "git:."

[minisat]

cmd = "minisat -cpu-lim=$timeout $file"
unsat = "^UNSATISFIABLE"
sat = "^SATISFIABLE"
unknown = "INDETERMINATE|INTERRUPTED"
version = "2.2"

[z3]

cmd = "./z3.sh $file -T:$timeout"
unsat = "^unsat$"
sat = "^sat$"
unknown = "^unknown$"
version = "4.8.4"

[msat]

cmd = "msat -time $timeout $file"
unsat = "^Unsat"
sat = "^Sat"
unknown = "Unknown"
version = "0.8"

[test]

timeout=30
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat", "z3" ]
dir = [ "benchs/msat/" ]

expect = "program:minisat"

[bench-basic]

timeout=30
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat", "z3" ]
dir = [ "benchs/basic" ]

expect = "unknown"

[bench-satrace-06]

timeout=30
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat", "z3" ]
dir = [ "benchs/sat_race_2006/" ]

expect = "unknown"
