
provers = [ "minisat-ml", "minisat", "msat" ]

[minisat-ml]

binary = "./minisat.exe"
cmd = "./minisat.exe -cpu-lim $timeout $file"
unsat = "^UNSAT"
sat = "^SAT"
unknown = "INDETERMINATE"
version = "git:."

[minisat]

cmd = "minisat -cpu-lim=$timeout $file"
unsat = "^UNSATISFIABLE"
sat = "^SATISFIABLE"
unknown = "INDETERMINATE"
version = "2.2"

[msat]

cmd = "msat -time $timeout $file"
unsat = "^Unsat"
sat = "^Sat"
unknown = "Unknown"
version = "0.8"

[test]

timeout=30
problems = ".*\\.cnf\\.*"
provers = [ "minisat-ml", "minisat", "msat" ]
dir = [ "benchs/msat/" ]

expect = "program:minisat"
